# TRACT Data - Local Data for Better Health
This dataset contains model-based census tract-level estimates for the PLACES 2021 release. 

PLACES is the expansion of the original 500 Cities project and covers the entire United States—50 states and the District of Columbia (DC)—at county, place, census tract, and ZIP Code Tabulation Area (ZCTA) levels. It represents a first-of-its kind effort to release information uniformly on this large scale for local areas at 4 geographic levels. Estimates were provided by the Centers for Disease Control and Prevention (CDC), Division of Population Health, Epidemiology and Surveillance Branch. PLACES was funded by the Robert Wood Johnson Foundation (RWJF) in conjunction with the CDC Foundation. The dataset includes estimates for 29 measures: 4 chronic disease-related health risk behaviors, 13 health outcomes, 3 health status, and 9 on use of preventive services. These estimates can be used to identify emerging health problems and to help develop and carry out effective, targeted public health prevention activities. Because the small area model cannot detect effects due to local interventions, users are cautioned against using these estimates for program or policy evaluations. Data sources used to generate these model-based estimates include Behavioral Risk Factor Surveillance System (BRFSS) 2019 or 2018 data, Census Bureau 2010 population data, and American Community Survey (ACS) 2015–019 or 2014–2018 estimates. The 2021 release uses 2019 BRFSS data for 22 measures and 2018 BRFSS data for 7 measures (all teeth lost, dental visits, mammograms, cervical cancer screening, colorectal cancer screening, core preventive services among older adults, and sleeping less than 7 hours a night). Seven measures are based on the 2018 BRFSS because the relevant questions are only asked every other year in the BRFSS. More information about the methodology can be found at www.cdc.gov/places.
Expand.


Link: https://chronicdata.cdc.gov/500-Cities-Places/PLACES-Local-Data-for-Better-Health-Census-Tract-D/cwsq-ngmh

# Connect to Shared Google drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
%cd 'drive/Shareddrives/ds1_final_project'
!ls

/content/drive/Shareddrives/ds1_final_project
PLACES__Local_Data_for_Better_Health__Census_Tract_Data_2021_release.csv

# Loading initial packages:

In [4]:
!pip install seaborn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: seaborn in /usr/local/lib/python3.7/dist-packages (0.11.2)
Requirement already satisfied: matplotlib>=2.2 in /usr/local/lib/python3.7/dist-packages (from seaborn) (3.2.2)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from seaborn) (1.21.6)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.7/dist-packages (from seaborn) (1.7.3)
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.7/dist-packages (from seaborn) (1.3.5)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2->seaborn) (0.11.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2->seaborn) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2->seaborn) (1.4.4)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2->seaborn) (2.8.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib>=2.2->seaborn) (4.1.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->seaborn) (2022.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=2.2->seaborn) (1.15.0)

In [5]:
## helpful packages

# Administrative stuff:
import os

# For Data manipulation:
import pandas as pd
import numpy as np
import random
import re

# Nice to haves
# ISSUE need to add geopandas
import matplotlib.pyplot as plt
from shapely.geometry import Point, Polygon
# import googlemaps
import plotly.graph_objects as go

## dynamic text updating
from IPython.display import Markdown as md

## repeated printouts
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## suppresses the traceback of an error
%xmode Minimal

Exception reporting mode: Minimal

In [6]:
import io
tract = pd.read_csv('PLACES__Local_Data_for_Better_Health__Census_Tract_Data_2021_release.csv')
# Dataset is now stored in a Pandas Dataframe

In [7]:
# Loading initial data:
#tract = pd.read_csv("PLACES__Local_Data_for_Better_Health__Census_Tract_Data_2021_release.csv")
#pd.unique(tract["StateDesc"])

tract_ky = tract[tract["StateDesc"] == "Kentucky"]
tract_ky.info()
tract_ky.head(n=5)
print(tract_ky.shape)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33170 entries, 3596 to 857829
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Year                        33170 non-null  int64
 1   StateAbbr                   33170 non-null  object
 2   StateDesc                   33170 non-null  object
 3   CountyName                  33170 non-null  object
 4   CountyFIPS                  33170 non-null  int64
 5   LocationName                33170 non-null  int64
 6   DataSource                  33170 non-null  object
 7   Category                    33170 non-null  object
 8   Measure                     33170 non-null  object
 9   Data_Value_Unit             33170 non-null  object
 10  Data_Value_Type             33170 non-null  object
 11  Data_Value                  33170 non-null  float64
 12  Data_Value_Footnote_Symbol  0 non-null      float64
 13  Data_Value_Footnote         0 non-null      float64
 14  Low_Confidence_Limit        33170 non-null  float64
 15  High_Confidence_Limit       33170 non-null  float64
 16  TotalPopulation             33170 non-null  int64
 17  Geolocation                 33170 non-null  object
 18  LocationID                  33170 non-null  int64
 19  CategoryID                  33170 non-null  object
 20  MeasureId                   33170 non-null  object
 21  DataValueTypeID             33170 non-null  object
 22  Short_Question_Text         33170 non-null  object
dtypes: float64(5), int64(5), object(13)
memory usage: 6.1+ MB

,Year,StateAbbr,StateDesc,CountyName,CountyFIPS,LocationName,DataSource,Category,Measure,Data_Value_Unit,...,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,Geolocation,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text
3596,2019,KY,Kentucky,Adair,21001,21001970300,BRFSS,Health Risk Behaviors,No leisure-time physical activity among adults...,%,...,NaN,41.5,48.3,3016,POINT (-85.15821669 37.13121962),21001970300,RISKBEH,LPA,CrdPrv,Physical Inactivity
3597,2019,KY,Kentucky,Adair,21001,21001970402,BRFSS,Health Outcomes,Stroke among adults aged >=18 years,%,...,NaN,3.0,3.6,4261,POINT (-85.26802881 37.12055109),21001970402,HLTHOUT,STROKE,CrdPrv,Stroke
3598,2019,KY,Kentucky,Anderson,21005,21005950201,BRFSS,Health Outcomes,Depression among adults aged >=18 years,%,...,NaN,25.5,27.9,5372,POINT (-84.92306901 38.02049683),21005950201,HLTHOUT,DEPRESSION,CrdPrv,Depression
3599,2019,KY,Kentucky,Bell,21013,21013960200,BRFSS,Health Outcomes,Stroke among adults aged >=18 years,%,...,NaN,5.4,6.4,5150,POINT (-83.73909778 36.76433928),21013960200,HLTHOUT,STROKE,CrdPrv,Stroke
3600,2019,KY,Kentucky,Bell,21013,21013960300,BRFSS,Health Outcomes,Stroke among adults aged >=18 years,%,...,NaN,5.0,6.2,2381,POINT (-83.61861461 36.71356868),21013960300,HLTHOUT,STROKE,CrdPrv,Stroke

(33170, 23)

# Column Analysis

To do: 
- subset to 2019 data - J
- drop columns: State name, DataSource, CategoryID, DataValueTypeID,Data_Value_Footnote - J 
- pivot categories column so there is one column for each health category (health outcome, health risk behaviors, prevention, and health status) - subset to the relvant health outcomes related to lungs (asthma, cancer, and chronic obstructive pulmonary disease) - J
- subset to relevant risk behaviors (including smoking...etc) - M
- subset to relevant prevention (look at the data) - M
- check if Data_Value_Footnote column has any non-null values DONE

In [8]:
## DataSource
len(pd.unique(tract_ky.DataSource))
pd.unique(tract_ky.DataSource)
# Only one data source: Behavioral Risk Factor Surveillance System (BRFSS)

1

array(['BRFSS'], dtype=object)

In [88]:
## Category and Measures
len(pd.unique(tract_ky.Category))
pd.unique(tract_ky.Category)
# Only 4 topics -> Do we reshape data based on this?

4

array(['Health Risk Behaviors', 'Health Outcomes', 'Prevention',
       'Health Status'], dtype=object)

In [10]:
tract_ky['Year'].unique()

array([2019, 2018])

In [119]:
tract_ky_2019 = tract_ky[tract_ky["Year"]==2019].copy()

## drop columns that we are not gonna use
tract_ky_2019_clean = tract_ky_2019.drop(['StateAbbr',"LocationName", 'DataSource','StateDesc', 'Measure', 'CategoryID','Data_Value_Footnote', 
                                          "Data_Value_Footnote_Symbol",'DataValueTypeID', "Short_Question_Text",],axis=1)
tract_ky_2019_clean.shape
tract_ky_2019_clean.head()

(24332, 13)

,Year,CountyName,CountyFIPS,Category,Data_Value_Unit,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,Geolocation,LocationID,MeasureId
3596,2019,Adair,21001,Health Risk Behaviors,%,Crude prevalence,44.8,41.5,48.3,3016,POINT (-85.15821669 37.13121962),21001970300,LPA
3597,2019,Adair,21001,Health Outcomes,%,Crude prevalence,3.3,3.0,3.6,4261,POINT (-85.26802881 37.12055109),21001970402,STROKE
3598,2019,Anderson,21005,Health Outcomes,%,Crude prevalence,26.6,25.5,27.9,5372,POINT (-84.92306901 38.02049683),21005950201,DEPRESSION
3599,2019,Bell,21013,Health Outcomes,%,Crude prevalence,5.8,5.4,6.4,5150,POINT (-83.73909778 36.76433928),21013960200,STROKE
3600,2019,Bell,21013,Health Outcomes,%,Crude prevalence,5.5,5.0,6.2,2381,POINT (-83.61861461 36.71356868),21013960300,STROKE

In [120]:
# ISSUE TO REVIEW 

#pivot categories column so there is one column for each health category (health outcome, health risk behaviors, prevention, and health status) 
##subset to the relvant health outcomes related to lungs (asthma, cancer, and chronic obstructive pulmonary disease) 
tract_ky_19 = tract_ky_2019.pivot_table(index='Category',observed=False)
tract_ky_19.shape
tract_ky_19.head(3)

(4, 8)

,CountyFIPS,Data_Value,High_Confidence_Limit,LocationID,LocationName,Low_Confidence_Limit,TotalPopulation,Year
Category,,,,,,,,
Health Outcomes,21110.238698,19.059803,19.847416,2.111065e+10,2.111065e+10,18.287229,3923.44123,2019
Health Risk Behaviors,21110.238698,24.931133,26.919048,2.111065e+10,2.111065e+10,22.933544,3923.44123,2019
Health Status,21110.238698,19.579325,21.315642,2.111065e+10,2.111065e+10,17.912116,3923.44123,2019

In [123]:
# create function to find unique measure IDs for each category
def unique_measures(df, category):
  df_sub = df[["Category","MeasureId"]]
  focus_category = df_sub[df_sub["Category"] == category]
  return focus_category.MeasureId.unique()

In [2]:
tract_ky_2019_clean

NameError: name 'tract_ky_2019_clean' is not defined

In [124]:
# print the unique measures for reference and use in the focus_measures function 
# see codebook for full measure descriptions

unique_measures(tract_ky_2019_clean, category = "Health Outcomes")
# we're interested in current asthma (CASTHMA), Chronic obstructive pulmonary disease among adults aged >=18 years' (COPD)
# nad Cancer (excluding skin cancer) among adults aged >=18 years (CANCER)
# Add depression!

unique_measures(tract_ky_2019_clean, category = "Prevention")
# we're interested in Visits to doctor for routine checkup within the past year among adults aged (CHECKUP) and 
# Current lack of health insurance among adults aged 18-64 years (ACCESS2)
# Add BPMED 

unique_measures(tract_ky_2019_clean, category = "Health Risk Behaviors")
# we're interested in Current smoking among adults aged >=18 years (CSMOKING) and 
# No leisure-time physical activity among adults aged >=18 years (LPA)

unique_measures(tract_ky_2019_clean, category = "Health Status")
# we're interested in Physical health not good for >=14 days among adults aged >=18 years (PHLTH) and
# Fair or poor self-rated health status among adults aged >=18 years' (GHLTH)
# Go for the mental health as well?

array(['STROKE', 'DEPRESSION', 'ARTHRITIS', 'CASTHMA', 'HIGHCHOL', 'CHD',
       'OBESITY', 'CANCER', 'BPHIGH', 'DIABETES', 'KIDNEY', 'COPD'],
      dtype=object)

array(['CHOLSCREEN', 'BPMED', 'ACCESS2', 'CHECKUP'], dtype=object)

array(['LPA', 'BINGE', 'CSMOKING'], dtype=object)

array(['PHLTH', 'MHLTH', 'GHLTH'], dtype=object)

In [125]:
# create a function to subset to focuse measures for each category
def focus_measures(df, category, measures):
  focus_category = df[df['Category'] == category]
  focus_measures = measures
  focus_category_measures = focus_category[focus_category["MeasureId"].isin(focus_measures)]
  return focus_category_measures

In [129]:
## create focus subsets

## subset of health outcomes of asthma, cancer, and Chronic obstructive pulmonary disease
health_outcomes_fm.head(2)

## subset of health preventions of routine checkups and health insurance access
health_prevention_fm = focus_measures(tract_ky_2019_clean, category="Prevention", measures=["CHECKUP", 'ACCESS2'])
health_prevention_fm.head(2)

## subset of health preventions of routine checkups and health insurance access
health_risk_fm = focus_measures(tract_ky_2019_clean, category="Health Risk Behaviors", measures=["CSMOKING", 'LPA'])
health_risk_fm.head(2)

## subset of health preventions of routine checkups and health insurance access
health_status_fm = focus_measures(tract_ky_2019_clean, category="Health Status", measures=["PHLTH", 'GHLTH'])
health_status_fm.head(2)

,Year,CountyName,CountyFIPS,Category,Data_Value_Unit,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,Geolocation,LocationID,MeasureId
3609,2019,Clark,21049,Health Outcomes,%,Crude prevalence,11.8,11.2,12.4,3107,POINT (-84.18804198 38.02446147),21049020201,CASTHMA
3627,2019,Floyd,21071,Health Outcomes,%,Crude prevalence,6.9,6.7,7.1,4877,POINT (-82.65130799 37.46649389),21071920400,CANCER

,Year,CountyName,CountyFIPS,Category,Data_Value_Unit,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,Geolocation,LocationID,MeasureId
3651,2019,Jefferson,21111,Prevention,%,Crude prevalence,17.2,15.4,19.0,2447,POINT (-85.78253076 38.2614617),21111002300,ACCESS2
3677,2019,Mason,21161,Prevention,%,Crude prevalence,82.4,81.9,82.9,4627,POINT (-83.88007329 38.65151689),21161960400,CHECKUP

,Year,CountyName,CountyFIPS,Category,Data_Value_Unit,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,Geolocation,LocationID,MeasureId
3596,2019,Adair,21001,Health Risk Behaviors,%,Crude prevalence,44.8,41.5,48.3,3016,POINT (-85.15821669 37.13121962),21001970300,LPA
3654,2019,Jefferson,21111,Health Risk Behaviors,%,Crude prevalence,15.9,14.0,17.9,6253,POINT (-85.52422538 38.234524),21111010402,CSMOKING

,Year,CountyName,CountyFIPS,Category,Data_Value_Unit,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,Geolocation,LocationID,MeasureId
3615,2019,Fayette,21067,Health Status,%,Crude prevalence,18.6,17.0,20.1,1567,POINT (-84.50254184 38.05169429),21067000102,PHLTH
3641,2019,Harrison,21097,Health Status,%,Crude prevalence,19.8,18.3,21.3,2833,POINT (-84.27118391 38.51614829),21097950100,PHLTH

In [14]:
## Measure
# len(pd.unique(tract_ky.Measure))
# pd.unique(tract_ky.Measure)
# 30 measures 
tract_ky_2019.groupby(["Category", "Measure"]).agg('count').reset_index()

,Category,Measure,Year,CountyName,CountyFIPS,LocationName,Data_Value_Unit,Data_Value_Type,Data_Value,Data_Value_Footnote_Symbol,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,Geolocation,LocationID,MeasureId,Short_Question_Text
0,Health Outcomes,Arthritis among adults aged >=18 years,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
1,Health Outcomes,Cancer (excluding skin cancer) among adults ag...,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
2,Health Outcomes,Chronic kidney disease among adults aged >=18 ...,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
3,Health Outcomes,Chronic obstructive pulmonary disease among ad...,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
4,Health Outcomes,Coronary heart disease among adults aged >=18 ...,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
5,Health Outcomes,Current asthma among adults aged >=18 years,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
6,Health Outcomes,Depression among adults aged >=18 years,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
7,Health Outcomes,Diagnosed diabetes among adults aged >=18 years,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
8,Health Outcomes,High blood pressure among adults aged >=18 years,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
9,Health Outcomes,High cholesterol among adults aged >=18 years ...,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
10,Health Outcomes,Obesity among adults aged >=18 years,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
11,Health Outcomes,Stroke among adults aged >=18 years,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
12,Health Risk Behaviors,Binge drinking among adults aged >=18 years,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
13,Health Risk Behaviors,Current smoking among adults aged >=18 years,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
14,Health Risk Behaviors,No leisure-time physical activity among adults...,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
15,Health Status,Fair or poor self-rated health status among ad...,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
16,Health Status,Mental health not good for >=14 days among adu...,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
17,Health Status,Physical health not good for >=14 days among a...,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
18,Prevention,Cholesterol screening among adults aged >=18 y...,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
19,Prevention,Current lack of health insurance among adults ...,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
20,Prevention,Taking medicine for high blood pressure contro...,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106
21,Prevention,Visits to doctor for routine checkup within th...,1106,1106,1106,1106,1106,1106,1106,0,1106,1106,1106,1106,1106,1106,1106

In [1]:
pd.unique(tract_ky_2019.CountyName)

NameError: name 'pd' is not defined